version: '3.8'

services:
  backend:
    image: digitalizr/node_backend:latest
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: 103.91.67.38
      DB_PORT: 5432
      DB_NAME: energy_management
